### ISSUE TITLE
Feature parent station

### ISSUE THREAD

**Issue by brechtvdv** [linkedconnections/csa.js#4] opened 2015-10-09 13:59 UTC
Some datasets only work with stops that are the combination of the parent_station and platform_code.

A connection should have `lc:arrivalParentStation` and `lc:departureParentStation` properties when available.

**Comment by pietercolpaert** [comment] 2015-10-09 14:05
- Concerning properties: use `gtfs:parentStation`. No need for the properties you suggest
- I believe this is a duplicate of https://github.com/linkedconnections/csa.js/issues/1

**Comment by pietercolpaert** [comment] 2015-10-12 15:41
I'll close this one for now as duplicate of #1

**Closed as completed by pietercolpaert** 2015-10-12 15:41 UTC
